# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Unity-iPhone' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Unity-iPhone

  target 'Unity-iPhone Tests' do
    inherit! :search_paths
    # Pods for testing
  end
target 'Unity-iPhone' do
  pod 'GoogleMobileAdsMediationUnityAdsSDK', '~> 2.1'
end
target 'Unity-iPhone' do
  pod 'Alamofire', '~> 4.5'
end
end
